# Generated by Django 3.2.25 on 2024-06-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fcuser',
            table='fcuser',
        ),
    ]
