# Generated by Django 3.2.25 on 2024-06-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_alter_fcuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': 'fc사용자', 'verbose_name_plural': 'fc사용자 리스트'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@gmailc.om', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
